#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#  
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# 
# HOW TO:
# curl -fL -H 'Cache-Control: no-cache, no-store' https://raw.githubusercontent.com/alrokayan/kubecsv/main/kubecsv | bash -s -- deploy.csv Asia/Riyadh ~/.kube/config
# $1 csv file
# $2 Time Zone
# $3 kubeconfig path
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage: $0 <CSV file> <Time Zone> <Kubeconfig file>"
    echo "EXAMPLE: $0 deploy.csv Asia/Riyadh ~/.kube/config"
    if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
        echo "This script will deploy applications from a CSV file"
        exit 0
    fi
    exit 1
fi
#######################################
#######################################
# FUNCTION createNetworkAttachmentDefinition_STATIC
#######################################
#######################################
function createNetworkAttachmentDefinition_STATIC() {
  cat <<EOF | kubectl --kubeconfig $KUBECONFIG_FILE create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: $BRIDGE_NAME
  namespace: $APP_NAMESPACE
spec:
  config: '{
      "cniVersion": "1.0.0",
      "name": "$BRIDGE_NAME",
      "plugins": [
        {
          "cniVersion": "1.0.0",
          "type": "macvlan",
          "mode": "bridge",
          "mac": "$MAC",
          "master": "$MASTER_NIC",
          "isDefaultGateway": true,
          "enableIPv6": false,
          "ipam": {
            "type": "static",
            "addresses":
            [
              {
                "address": "$IPCIDR", 
                "gateway": "$GW"
              }
            ],
            "routes":
            [
              {
                "dst": "0.0.0.0/0"
              }
            ]
          },
          "dns":
          {
            "nameservers":
            [
              "$DNS1",
              "$DNS2" 
            ]
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          },
          "snat": true
        },
        {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
EOF
  ssh -i "$PRIVATE_KEY" $SSH_EXTRA_ARGS "$SSH_USERNAME"@"${NODE_ARRAY[0]}" DEBIAN_FRONTEND="noninteractive" "bash -s" <<'____EOF____'
#!/bin/bash
ip link show type bridge
ip link show type veth
bridge link show
____EOF____
}

#######################################
#######################################
# FUNCTION createNetworkAttachmentDefinition_DHCP
#######################################
#######################################
function createNetworkAttachmentDefinition_DHCP() {
  cat <<EOF | kubectl --kubeconfig $KUBECONFIG_FILE create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: $BRIDGE_NAME
  namespace: $APP_NAMESPACE
spec:
  config: '{
      "cniVersion": "1.0.0",
      "name": "$BRIDGE_NAME",
      "plugins": [
        {
          "cniVersion": "1.0.0",
          "type": "macvlan",
          "mode": "bridge",
          "mac": "$MAC",
          "master": "$MASTER_NIC",
          "isDefaultGateway": true,
          "enableIPv6": false,
          "ipam": {
            "type": "dhcp",
            "routes":
            [
              {
                "dst": "0.0.0.0/0"
              }
            ],
            "daemonSocketPath": "/run/cni/dhcp.sock",
            "request": [
              {
                  "skipDefault": false
              }
            ],
            "provide": [
              {
                "option": "host-name",
                "fromArg": "k8s-$APP_NAMESPACE"
              }
            ]
          },
          "dns":
          {
            "nameservers":
            [
              "$DNS1",
              "$DNS2"
            ]
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          },
          "snat": true
        },
        {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
EOF
}

#######################################
#######################################
########## FUNCTION deployAPP #########
#######################################
#######################################
function deployAPP() {
  if [ "$GW" == "" ]; then
    VALUES+="--set 'workload.main.podSpec.annotations.k8s\.v1\.cni\.cncf\.io/networks=$NETWORK_ANNOTATION' --set TZ=$TZ"
  else
    VALUES+="--set 'workload.main.podSpec.annotations.k8s\.v1\.cni\.cncf\.io/networks=[$NETWORK_ANNOTATION]' --set TZ=$TZ"
  fi
  VALUES="${VALUES//$'\r'/}"
  echo "csv raw $(($j - 1)) -- $CURRENT_APP: Deploying .." 
  echo "with values: $VALUES"
  echo
  echo -n "-- kubecsv added the following values: "
  echo "${VALUES//--set/$'\n# --set'}"
  NEW_APP_RAW=true
  APP_NAMESPACE="app-$CURRENT_APP"
  CMD="helm --kubeconfig $KUBECONFIG_FILE upgrade --install $CURRENT_APP --namespace $APP_NAMESPACE --create-namespace oci://tccr.io/truecharts/$CURRENT_HELM_CHART $VALUES"
  echo "-- Running command: $CMD"
  eval "$CMD"
  # echo "-- $CURRENT_APP is been deployed .." 
  unset VALUES
  unset NETWORK_ANNOTATION
}

#######################################
#######################################
######## FUNCTION binInstall ##########
#######################################
#######################################
function binInstall() {
  if [[ "$(uname -s)" == *"Linux"* ]]; then
    echo "-- OS: Linux - CHECKING BINARIES" 
    if ! command -v helm &> /dev/null; then
      curl -L https://get.helm.sh/helm-v3.15.2-linux-"$(dpkg --print-architecture)".tar.gz -o tmp/helm.tar.gz
      tar -zxf tmp/helm.tar.gz -C tmp
      sudo mv tmp/linux-"$(dpkg --print-architecture)"/helm /usr/local/bin/
      sudo chmod +x /usr/local/bin
      if command -v helm &> /dev/null; then echo "-- helm installed successfully" ; fi
    fi
    if ! command -v kubectl &> /dev/null; then
      sudo curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/$(dpkg --print-architecture)/kubectl" -o /usr/local/bin/kubectl
      sudo chmod +x /usr/local/bin/kubectl
      if command -v kubectl &> /dev/null; then echo "-- kubectl installed successfully" ; fi
    fi
  fi
  if [[ "$(uname -s)" == *"Darwin"* ]]; then
    echo "-- OS: macOS - CHECKING BINARIES" 
    if ! command -v helm &> /dev/null; then
      curl -L "https://get.helm.sh/helm-v3.15.2-darwin-$(arch).tar.gz" -o tmp/helm.tar.gz
      tar -zxf tmp/helm.tar.gz -C tmp
      sudo mv tmp/darwin-"$(arch)"/helm /usr/local/bin/
      sudo chmod +x /usr/local/bin/helm
      if command -v helm &> /dev/null; then echo "-- helm installed successfully" ; fi
    fi
    if ! command -v kubectl &> /dev/null; then
      sudo curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/$(arch)/kubectl" -o /usr/local/bin/kubectl
      sudo chmod +x /usr/local/bin/kubectl
      if command -v kubectl &> /dev/null; then echo "-- kubectl installed successfully" ; fi
    fi
  fi
  helm version
  kubectl version --client=true
}


##############################################################################
binInstall
export CSVFILE="$1"
export TZ="$2"
export KUBECONFIG_FILE="$3"
if [ "$CSVFILE" == "" ]; then CSVFILE="deploy.csv"; fi
if [ "$TZ" == "" ]; then TZ="Asia/Riyadh"; fi
if [ "$KUBECONFIG_FILE" == "" ]; then KUBECONFIG_FILE=$KUBECONFIG; fi
if ! [ -f "$CSVFILE" ]; then echo "CSV file could not be found"; exit 1; fi
if ! [ -f "$KUBECONFIG_FILE" ]; then echo "kubeconfig file could not be found"; exit 1; fi

NEW_APP_RAW=true
j=1
while IFS="," read -r app_name helm_truechart storage_name storage_enabled storage_path storage_subPath storage_server storage_type storage_mountPath nw_master_nic nw_mac nw_address_with_subnet nw_gateway nw_dns1 nw_dns2 run_as_user run_as_group privileged extra_helm_values; do
  if (($j > 1)) && [ "$app_name" != "$CURRENT_APP" ]; then
    deployAPP
  fi
  CURRENT_APP="$app_name"
  CURRENT_HELM_CHART="$helm_truechart"
  APP_NAMESPACE="app-$CURRENT_APP"
  if $NEW_APP_RAW; then
    echo "csv raw $j -- $app_name: Building values  .."
    kubectl --kubeconfig $KUBECONFIG_FILE create ns "$APP_NAMESPACE"
    NEW_APP_RAW=false
  fi
  if [ "$storage_name" != "" ]; then
    echo "csv raw $j -- $app_name: Adding storage configuration \"$storage_name\" to the values .."  
    if [ "$storage_enabled" != "" ]; then
      VALUES+="--set persistence.$storage_name.enabled=$storage_enabled "
    fi
    if [ "$storage_path" != "" ]; then
      VALUES+="--set persistence.$storage_name.path=\"$storage_path\" "
    fi
    if [ "$storage_subPath" != "" ]; then
      VALUES+="--set persistence.$storage_name.subPath=\"$storage_subPath\" "
    fi
    if [ "$storage_server" != "" ]; then
      VALUES+="--set persistence.$storage_name.server=\"$storage_server\" "
    fi
    if [ "$storage_type" != "" ]; then
      VALUES+="--set persistence.$storage_name.type=\"$storage_type\" "
    fi
    if [ "$storage_mountPath" != "" ]; then
      VALUES+="--set persistence.$storage_name.mountPath=\"$storage_mountPath\" "
    fi
  fi
  if [ "$nw_master_nic" != "" ]; then
    MAC=$nw_mac
    MAC_REGEX="^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$"
    if ! [[ $MAC =~ $MAC_REGEX ]]; then MAC="$(printf '00:2F:60:%02X:%02X:%02X\n' $(shuf -i 0-99 -n 1) $(shuf -i 101-199 -n 1) $(shuf -i 201-256 -n 1))"; fi
    export MASTER_NIC="$nw_master_nic"
    export BRIDGE_NAME=cbr-${nw_master_nic//@/-}
    export APP_NAMESPACE
    export MAC
    export DNS1=$nw_dns1
    export DNS2=$nw_dns2
    export GW=$nw_gateway
    export IPCIDR=$nw_address_with_subnet
    IP=$(echo "$IPCIDR" | cut -d'/' -f1)
    kubectl --kubeconfig $KUBECONFIG_FILE delete network-attachment-definitions.k8s.cni.cncf.io "$BRIDGE_NAME" -n "$APP_NAMESPACE"
    if [[ $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo "csv raw $j -- $app_name: Adding STATIC IP ($nw_address_with_subnet) ($MAC) network configuration $nw_master_nic to the values .." 
      createNetworkAttachmentDefinition_STATIC
    else
      echo "csv raw $j -- $app_name: Adding DHCP ($MAC) network configuration $nw_master_nic to the values .." 
      createNetworkAttachmentDefinition_DHCP
    fi
    if [ "$GW" == "" ]; then
      if [ "$NETWORK_ANNOTATION" == "" ]; then
        NETWORK_ANNOTATION="$BRIDGE_NAME"
      else
        NETWORK_ANNOTATION+="\,$BRIDGE_NAME"
      fi
    else
      if [ "$NETWORK_ANNOTATION" == "" ]; then
        NETWORK_ANNOTATION="{\"name\": \"$BRIDGE_NAME\"\,\"default-route\": [\"$GW\"]}"
      else
        NETWORK_ANNOTATION+=",{\"name\": \"$BRIDGE_NAME\"\,\"default-route\": [\"$GW\"]}"
      fi
    fi
    if [ "$DNS1" != "" ] || [ "$DNS2" != "" ]; then
      echo "csv raw $j -- $app_name: Adding dnsPolicy=ClusterFirstWithHostNet to the values .." 
      VALUES+="--set workload.main.podSpec.dnsPolicy=ClusterFirstWithHostNet "
      VALUES+="--set podOptions.dnsPolicy=ClusterFirstWithHostNet "
      if [ "$DNS1" != "" ]; then
        echo "csv raw $j -- $app_name: Adding DNS1=$DNS1 to the values .." 
        VALUES+="--set workload.main.podSpec.dnsConfig.nameservers[0]=\"$DNS1\" "
      fi
      if [ "$DNS2" != "" ]; then
          echo "csv raw $j -- $app_name: Adding DNS2=$DNS2 to the values .." 
        VALUES+="--set workload.main.podSpec.dnsConfig.nameservers[1]=\"$DNS2\" "
      fi
    fi
  fi
  if [ "$run_as_user" != "" ]; then
    echo "csv raw $j -- $app_name: Adding runAsUser: $run_as_user to the values .." 
    VALUES+="--set securityContext.container.runAsUser=$run_as_user "
    VALUES+="--set securityContext.container.PUID=$run_as_user "
  fi
  if [ "$run_as_group" != "" ]; then
    echo "csv raw $j -- $app_name: Adding runAsGroup: $run_as_group to the values .." 
    VALUES+="--set securityContext.container.runAsGroup=$run_as_group "
    VALUES+="--set securityContext.pod.fsGroup=$run_as_group "
  fi
  if [ "$privileged" != "" ]; then
    echo "csv raw $j -- $app_name: Adding privileged: $privileged to the values .." 
    VALUES+="--set securityContext.container.privileged=$privileged "
    VALUES+="--set securityContext.container.UMASK=000 "
    VALUES+="--set securityContext.container.runAsNonRoot=false "
    VALUES+="--set securityContext.container.readOnlyRootFilesystem=false "
  fi
  if [ "$extra_helm_values" != "" ]; then
    echo "csv raw $j -- $app_name: Adding extra values: $extra_helm_values .." 
    VALUES+="$extra_helm_values "
  fi
  j=$(($j + 1))
done < <(tail -n +2 $1)
deployAPP
